import logging
import re

import httpx

from app.config import settings
from app.prompt_builder import SYSTEM_PROMPT, build_user_prompt
from app.schemas import ImpresionClinicaRequest

logger = logging.getLogger(__name__)

ABBREVIATIONS = {
    "O.D.": "__ABBR_OD__",
    "O.I.": "__ABBR_OI__",
    "Dr.": "__ABBR_DR__",
    "Dra.": "__ABBR_DRA__",
    "No.": "__ABBR_NO__",
    "Av.": "__ABBR_AV__",
    "Esf.": "__ABBR_ESF__",
    "Cil.": "__ABBR_CIL__",
    "Eje.": "__ABBR_EJE__",
    "Sr.": "__ABBR_SR__",
    "Sra.": "__ABBR_SRA__",
    "p. ej.": "__ABBR_PEJ__",
    "p.ej.": "__ABBR_PEJ2__",
}

LIST_BULLET_RE = re.compile(r"^(?:[-*•])\s+")
LIST_NUMBER_RE = re.compile(r"^\d+\.\s+")
MULTISPACE_RE = re.compile(r"\s+")
SENTENCE_END_RE = re.compile(r"(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÑ])")


def _protect_abbreviations(text: str) -> str:
    for abbr, token in ABBREVIATIONS.items():
        text = text.replace(abbr, token)
    return text


def _restore_abbreviations(text: str) -> str:
    for abbr, token in ABBREVIATIONS.items():
        text = text.replace(token, abbr)
    return text


def _split_sentences(text: str) -> list[str]:
    """Split sentences without breaking common clinical abbreviations."""
    if not text:
        return []

    clean = MULTISPACE_RE.sub(" ", text).strip()
    if not clean:
        return []

    protected = _protect_abbreviations(clean)
    parts = SENTENCE_END_RE.split(protected)

    sentences = []
    for part in parts:
        restored = _restore_abbreviations(part).strip()
        if restored:
            sentences.append(restored)

    return sentences


def _normalize_sentence(text: str) -> str:
    text = MULTISPACE_RE.sub(" ", text.strip())
    text = text.rstrip(".!?")
    return text.lower()


def _strip_leading_list_markers(line: str) -> str:
    line = LIST_BULLET_RE.sub("", line)
    line = LIST_NUMBER_RE.sub("", line)
    return line.strip()


def _postprocess(text: str) -> str:
    """Clean and constrain model output."""
    text = re.sub(r"^```\w*\n?", "", text.strip())
    text = re.sub(r"\n?```\s*$", "", text)
    text = text.strip("`").strip()

    cleaned_lines = []
    for line in text.splitlines():
        line = _strip_leading_list_markers(line.strip())
        if line:
            cleaned_lines.append(line)

    text = " ".join(cleaned_lines)
    text = MULTISPACE_RE.sub(" ", text).strip()

    sentences = _split_sentences(text)
    if settings.max_sentences > 0 and len(sentences) > settings.max_sentences:
        sentences = sentences[: settings.max_sentences]

    text = " ".join(sentences).strip()

    if text and not text.endswith("."):
        text = f"{text}."

    if not text:
        raise ValueError("Model returned empty output after postprocessing")

    return text


def _ensure_follow_up_last(text: str, recommendation: str | None) -> str:
    """
    Append the structured follow-up as the final sentence.

    The model does NOT receive follow-up data and is instructed not to
    generate follow-up text.  This function is the single authority for
    inserting the follow-up recommendation.

    A normalised exact-match check on the last sentence is kept as a
    safety net in case the 7B model produces one despite instructions.
    """
    if not recommendation:
        return text

    follow_up = MULTISPACE_RE.sub(" ", recommendation.strip())
    if not follow_up:
        return text
    if not follow_up.endswith("."):
        follow_up = f"{follow_up}."

    sentences = _split_sentences(text)

    normalized_follow_up = _normalize_sentence(follow_up)
    if sentences and _normalize_sentence(sentences[-1]) == normalized_follow_up:
        logger.info("Removed duplicate follow-up sentence generated by model")
        sentences = sentences[:-1]

    if settings.max_sentences > 0:
        max_base = max(settings.max_sentences - 1, 0)
        if len(sentences) > max_base:
            sentences = sentences[:max_base]

    sentences.append(follow_up)

    final_text = " ".join(s.strip() for s in sentences if s.strip()).strip()
    final_text = MULTISPACE_RE.sub(" ", final_text)

    if final_text and not final_text.endswith("."):
        final_text += "."

    return final_text


async def run_inference(
    payload: ImpresionClinicaRequest,
    client: httpx.AsyncClient,
) -> str:
    user_prompt = build_user_prompt(payload)

    request_body = {
        "model": settings.ollama_model,
        "prompt": user_prompt,
        "system": SYSTEM_PROMPT,
        "stream": False,
        "options": {
            "temperature": settings.ollama_temperature,
            "num_predict": settings.ollama_num_predict,
        },
    }

    last_error: Exception | None = None
    for attempt in range(2):
        try:
            response = await client.post(
                f"{settings.ollama_url}/api/generate",
                json=request_body,
            )
            response.raise_for_status()
            break
        except httpx.ReadTimeout as exc:
            last_error = exc
            if attempt == 0:
                logger.warning(
                    "Ollama read timeout (attempt 1), retrying — "
                    "model may be loading into VRAM"
                )
                continue
            raise
    else:
        raise last_error  # type: ignore[misc]

    data = response.json()
    raw_text = data.get("response", "")

    done_reason = data.get("done_reason", "")
    if done_reason == "length":
        logger.warning(
            "Model output truncated by num_predict limit (%d tokens). "
            "Raw tail: '...%s'",
            settings.ollama_num_predict,
            raw_text[-80:],
        )

    try:
        text = _postprocess(raw_text)
    except ValueError:
        logger.error(
            "Model output empty after postprocessing. Raw output: '%s'",
            raw_text[:200],
        )
        raise

    return _ensure_follow_up_last(text, payload.clinica.recomendacion_seguimiento)
