import logging
import re

import httpx

from app.config import settings
from app.prompt_builder import build_system_prompt, build_user_prompt
from app.schemas import ImpresionClinicaRequest

logger = logging.getLogger(__name__)

ABBREVIATIONS = {
    "O.D.":  "__ABBR_OD__",
    "O.I.":  "__ABBR_OI__",
    "A.O.":  "__ABBR_AO__",
    "Dr.":   "__ABBR_DR__",
    "Dra.":  "__ABBR_DRA__",
    "No.":   "__ABBR_NO__",
    "Av.":   "__ABBR_AV__",
    "Esf.":  "__ABBR_ESF__",
    "Cil.":  "__ABBR_CIL__",
    "Eje.":  "__ABBR_EJE__",
    "Sr.":   "__ABBR_SR__",
    "Sra.":  "__ABBR_SRA__",
    "p. ej.":"__ABBR_PEJ__",
    "p.ej.": "__ABBR_PEJ2__",
    "D.":    "__ABBR_D__",
    "mmHg.": "__ABBR_MMHG__",
    "s.c.":  "__ABBR_SC__",
    "c.c.":  "__ABBR_CC__",
    "seg.":  "__ABBR_SEG__",
    "cm.":   "__ABBR_CM__",
}

LIST_BULLET_RE  = re.compile(r"^(?:[-*•])\s+")
LIST_NUMBER_RE  = re.compile(r"^\d{1,2}\.\s+(?=[A-ZÁÉÍÓÚÑ])")
MULTISPACE_RE   = re.compile(r"\s+")
SENTENCE_END_RE = re.compile(r"(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÑ])")
THINK_BLOCK_RE  = re.compile(r"<think>.*?</think>", re.DOTALL)


def _protect_abbreviations(text: str) -> str:
    for abbr, token in ABBREVIATIONS.items():
        text = text.replace(abbr, token)
    return text


def _restore_abbreviations(text: str) -> str:
    for abbr, token in ABBREVIATIONS.items():
        text = text.replace(token, abbr)
    return text


def _split_sentences(text: str) -> list[str]:
    if not text:
        return []
    clean = MULTISPACE_RE.sub(" ", text).strip()
    if not clean:
        return []
    protected = _protect_abbreviations(clean)
    parts = SENTENCE_END_RE.split(protected)
    sentences = []
    for part in parts:
        restored = _restore_abbreviations(part).strip()
        if restored:
            sentences.append(restored)
    return sentences


def _normalize_sentence(text: str) -> str:
    text = MULTISPACE_RE.sub(" ", text.strip())
    text = text.rstrip(".!?")
    return text.lower()


def _strip_leading_list_markers(line: str) -> str:
    line = LIST_BULLET_RE.sub("", line)
    line = LIST_NUMBER_RE.sub("", line)
    return line.strip()


def _postprocess(text: str) -> str:
    # Elimina bloques <think> que Qwen 3.5 puede generar aunque think=False.
    # El segundo sub captura bloques incompletos (truncados por num_predict).
    text = THINK_BLOCK_RE.sub("", text.strip()).strip()
    text = re.sub(r"<think>.*$", "", text, flags=re.DOTALL).strip()

    text = re.sub(r"^```\w*\n?", "", text)
    text = re.sub(r"\n?```\s*$", "", text)
    text = text.strip("`").strip()

    cleaned_lines = []
    for line in text.splitlines():
        line = _strip_leading_list_markers(line.strip())
        if line:
            cleaned_lines.append(line)

    text = " ".join(cleaned_lines)
    text = MULTISPACE_RE.sub(" ", text).strip()
    sentences = _split_sentences(text)
    text = " ".join(sentences).strip()

    if text and not text.endswith("."):
        text = f"{text}."

    if not text:
        raise ValueError("Model returned empty output after postprocessing")

    return text


def _ensure_follow_up_last(text: str, recommendation: str | None) -> str:
    """
    Agrega la recomendación de seguimiento al final del párrafo.

    El system prompt ya fue construido con effective_max = max_sentences - 1
    cuando hay recomendación, así que el modelo dejó espacio y no hay truncamiento.
    Esta función solo remueve duplicados y asegura posición final.
    """
    if not recommendation:
        return text

    follow_up = MULTISPACE_RE.sub(" ", recommendation.strip())
    if not follow_up:
        return text
    if not follow_up.endswith("."):
        follow_up = f"{follow_up}."

    sentences = _split_sentences(text)

    # Remover si el modelo ya incluyó la recomendación (detección exacta)
    normalized_follow_up = _normalize_sentence(follow_up)
    if sentences and _normalize_sentence(sentences[-1]) == normalized_follow_up:
        logger.info("Removed duplicate follow-up sentence generated by model")
        sentences = sentences[:-1]

    # Detección semántica de seguimiento parafraseado por el modelo.
    # Requiere al menos 2 keywords simultáneas para evitar falsos positivos
    # con oraciones clínicas que usen "control" en otro contexto.
    follow_up_keywords = {"seguimiento", "revision", "control", "valoracion", "cita", "proxima"}
    if sentences:
        last_words = set(_normalize_sentence(sentences[-1]).split())
        matched = last_words & follow_up_keywords
        if len(matched) >= 2:
            logger.warning(
                "Removed semantically duplicate follow-up from model output "
                "(matched keywords: %s)", matched
            )
            sentences = sentences[:-1]

    sentences.append(follow_up)

    final_text = " ".join(s.strip() for s in sentences if s.strip()).strip()
    final_text = MULTISPACE_RE.sub(" ", final_text)

    if final_text and not final_text.endswith("."):
        final_text += "."

    return final_text


async def run_inference(
    payload: ImpresionClinicaRequest,
    client: httpx.AsyncClient,
) -> str:
    # Calcular effective_max ANTES de construir el prompt
    # Si hay recomendación, el modelo debe dejar una oración libre para ella
    has_recommendation = bool(payload.clinica.recomendacion_seguimiento)
    effective_max = settings.max_sentences - 1 if has_recommendation else settings.max_sentences

    system_prompt = build_system_prompt(effective_max)
    user_prompt = build_user_prompt(payload)

    request_body = {
        "model": settings.ollama_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        "stream": False,
        "think":  False,
        "options": {
            "temperature":    settings.ollama_temperature,
            "num_predict":    settings.ollama_num_predict,
            "num_ctx":        settings.ollama_num_ctx,
            "repeat_penalty": settings.ollama_repeat_penalty,
            "top_p":          settings.ollama_top_p,
            "seed":           settings.ollama_seed,
        },
    }

    last_error: Exception | None = None
    data: dict = {}
    raw_text = ""

    for attempt in range(settings.ollama_max_retries):
        try:
            response = await client.post(
                f"{settings.ollama_url}/api/chat",
                json=request_body,
            )
            response.raise_for_status()
            data = response.json()
            raw_text = data.get("message", {}).get("content", "")

            if not raw_text.strip():
                raise ValueError(
                    f"Ollama returned empty response "
                    f"(done_reason={data.get('done_reason', 'unknown')})"
                )
            break

        except (httpx.ReadTimeout, ValueError) as exc:
            last_error = exc
            if attempt == 0:
                logger.warning("Attempt 1 failed (%s), retrying...", type(exc).__name__)
                continue
            raise

        except httpx.HTTPStatusError as exc:
            # Solo reintentar en errores transitorios del servidor (500, 503)
            if exc.response.status_code in (500, 503) and attempt == 0:
                last_error = exc
                logger.warning(
                    "Attempt 1 failed (HTTP %d), retrying...",
                    exc.response.status_code,
                )
                continue
            raise
    else:
        raise last_error  # type: ignore[misc]

    done_reason = data.get("done_reason", "")
    if done_reason == "length":
        logger.warning(
            "Model output truncated by num_predict limit (%d tokens). "
            "Output length: %d chars. Consider increasing OLLAMA_NUM_PREDICT.",
            settings.ollama_num_predict,
            len(raw_text),
        )

    prompt_eval_count = data.get("prompt_eval_count", 0)
    ctx_margin = settings.ollama_num_ctx - settings.ollama_num_predict - prompt_eval_count
    if prompt_eval_count:
        logger.debug(
            "Context usage: %d input tokens, %d reserved for output, %d margin "
            "(num_ctx=%d)",
            prompt_eval_count,
            settings.ollama_num_predict,
            ctx_margin,
            settings.ollama_num_ctx,
        )
        if ctx_margin < 100:
            logger.warning(
                "Context margin critically low: %d tokens remaining. "
                "Input tokens: %d. Consider increasing OLLAMA_NUM_CTX.",
                ctx_margin,
                prompt_eval_count,
            )

    try:
        text = _postprocess(raw_text)
    except ValueError:
        logger.error(
            "Model output empty after postprocessing. Raw length: %d chars, done_reason: '%s'",
            len(raw_text),
            done_reason,
        )
        raise

    return _ensure_follow_up_last(text, payload.clinica.recomendacion_seguimiento)